"""SVG renderer.

Deterministic radial layout — hubs in the centre ring, consumers in
concentric arcs around them. Pure stdlib (``xml.etree.ElementTree`` for
the XML tree + ``math`` for trig). No GraphViz binary dep.

The SVG is *not* a pretty-print of the input — it is a Mirror-Mark
verifiable artefact:

* Node colour encodes :class:`~dep_map.scanner.NodeKind`.
* Node size encodes hub-status (HUBs render at 1.5× radius).
* Edge stroke encodes substrate — Go is solid, Rust is dashed,
  Python is dotted, TS is dash-dot, BEAM is double-stroke.
* Cohort firewall edges (R145.C, producer in
  :data:`~dep_map.graph.FIREWALL_HUBS`) are bolded to triple stroke
  width.
* Every emitted SVG carries:

  - An XML comment ``<!-- lore@v1: <mark> -->`` derived by HMAC-SHA256
    over the canonical SVG body (post-comment-stripping) with the
    cohort dev-key. Verifiable cold by ``lore-mark-verify verify``.
  - An R166 LIABILITY_FOOTER_CONST literal as an in-SVG ``<text>``
    element footer.
  - An R143 LOUD-ONCE wire on parse failure (delegated to scanner).

R145 stdlib-only — the renderer imports ``base64``, ``hashlib``, ``hmac``,
``math``, ``xml.etree.ElementTree``. Nothing else.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import math
import xml.etree.ElementTree as ET
from typing import Iterable

from dep_map.graph import FIREWALL_HUBS, Graph
from dep_map.scanner import HUB_NAMES, NodeKind


# ---------------------------------------------------------------------------
# R166 LIABILITY-FOOTER-CONST — byte-identical shape across cohort
# substrates. The dep-map flavour mirrors the cohort-walker footer
# (`tools/cohort-walker/cohort/legal/liability_footer.go`) but names the
# dep-map tool explicitly.
# ---------------------------------------------------------------------------

LIABILITY_FOOTER = (
    "[NOT LEGAL ADVICE — TOOL OUTPUT FOR INFORMATIONAL USE ONLY] "
    "This dependency map is generated by dep-map, an automated cross-cohort "
    "manifest walker. It reports declared edges in go.mod / Cargo.toml / "
    "pyproject.toml / package.json / rebar.config / mix.exs. It does NOT "
    "adjudicate whether a flagship is fit for any regulated purpose, nor "
    "whether the absence of an edge means the flagship is non-compliant. "
    "Operators MUST treat each missing or unexpected edge as a prompt to "
    "investigate, not as a finding of fault."
)

LIABILITY_TAG = "R166_LIABILITY_FOOTER_CONST"


# ---------------------------------------------------------------------------
# L43 Mirror-Mark v1 — pin canonical inputs to the cohort literals so the
# stamp is round-trip-verifiable against ``lore-mark-verify``.
# ---------------------------------------------------------------------------

# Mark-version byte: 0x01 means "Mirror-Mark v1". Identical to the cohort
# canonical in `engines/oracle/internal/mirrormark/mark.go` line 60.
MARK_VERSION = 0x01

# Header-value prefix that lets a downstream cold-verifier identify a v1
# mark and reject unknown versions.
MARK_PREFIX = "lore@v1:"

# Corpus-SHA prefix length and unencoded body length. The 8-byte prefix
# is the load-bearing diagnostic — it short-circuits to ErrCorpusMismatch
# when the wrong corpus is supplied, before the more-expensive HMAC step.
MARK_CORPUS_PREFIX_LEN = 8
MARK_BODY_LEN = MARK_CORPUS_PREFIX_LEN + hashlib.sha256().digest_size

# Dev-key used to stamp emitted SVGs. Documented placeholder. NOT a
# production key. Production stamps would use a corpus-bound key issued
# by the cohort lore service. Byte-identical to the placeholder in
# ``apps/lore-mark-verify/testdata/dev_receipt_key.bin``.
DEV_KEY = b"iik_dev_lore_mark_verify_phase1"

# Cohort-canonical dev corpus SHA. Hex literal pinned so a downstream
# cold-verifier can supply the same bytes via ``--corpus-sha-hex``. The
# value here is the SHA-256 of the dep-map repo's README intent string;
# it is not a registry handle. Operators stamping production SVGs MUST
# override via :func:`render_svg`'s ``corpus_sha`` parameter.
DEV_CORPUS_SHA = hashlib.sha256(
    b"limitless-dep-map dev corpus v1\n"
).digest()


def sign(corpus_sha: bytes, payload: bytes, key: bytes) -> str:
    """Re-derive the canonical Mirror-Mark for ``(corpus_sha, payload, key)``.

    Pure transcription of ``apps/lore-mark-verify/internal/verify`` Sign().
    The transcription is intentional — importing the Go binary's verify
    package would defeat the regulator-grade "no Limitless source trust
    required" property.

    Algorithm:

    1. ``HMAC-SHA256(key, 0x01 || corpus_sha || payload)`` -> 32-byte digest.
    2. body = ``corpus_sha[:8] || digest``.
    3. mark = ``"lore@v1:" || base64.urlsafe_b64encode(body).rstrip("=")``.

    The base64 step uses URL-safe alphabet with **no padding**, matching
    ``base64.RawURLEncoding`` in the Go canonical.
    """
    if len(corpus_sha) != hashlib.sha256().digest_size:
        raise ValueError(
            f"corpus_sha must be {hashlib.sha256().digest_size} bytes, got {len(corpus_sha)}"
        )
    mac = hmac.new(key, digestmod=hashlib.sha256)
    mac.update(bytes([MARK_VERSION]))
    mac.update(corpus_sha)
    mac.update(payload)
    digest = mac.digest()  # 32 bytes
    body = corpus_sha[:MARK_CORPUS_PREFIX_LEN] + digest
    assert len(body) == MARK_BODY_LEN
    encoded = base64.urlsafe_b64encode(body).rstrip(b"=").decode("ascii")
    return MARK_PREFIX + encoded


# ---------------------------------------------------------------------------
# Colour palette — keyed by NodeKind. Values are CSS hex strings. The
# palette is deliberately high-contrast and prints legibly on white.
# ---------------------------------------------------------------------------

NODE_FILL: dict[NodeKind, str] = {
    NodeKind.FLAGSHIP: "#4a90e2",        # cobalt — most-common, the focus layer
    NodeKind.INFRASTRUCTURE: "#e67e22",  # amber — infra distinct from flagships
    NodeKind.ENGINE: "#9b59b6",          # violet — engines (oracle/echo/parallax)
    NodeKind.FOUNDATION: "#2ecc71",      # emerald — foundation hub colour
    NodeKind.SDK: "#16a085",             # teal — SDKs
    NodeKind.HUB: "#c0392b",             # crimson — cohort hubs stand out hardest
    NodeKind.UNKNOWN: "#95a5a6",         # grey — unclassified
}

# Substrate-discriminator stroke pattern. Substrate name -> SVG
# ``stroke-dasharray`` value (``""`` = solid).
SUBSTRATE_STROKE: dict[str, str] = {
    "go": "",                  # solid — Go is the cohort majority
    "rust": "6,3",             # dashed
    "python": "2,3",           # dotted
    "ts": "6,3,2,3",           # dash-dot
    "beam": "1,2,1,2",         # double-stroke approximation via tight dashes
}


# ---------------------------------------------------------------------------
# Layout — pure deterministic geometry.
# ---------------------------------------------------------------------------

def _layout(graph: Graph, width: int, height: int) -> dict[str, tuple[float, float]]:
    """Compute deterministic ``node -> (x, y)`` positions.

    Layout strategy:

    1. Hubs (nodes in :data:`HUB_NAMES`) go on an **inner ring** at
       40 % of the half-diagonal radius. Inside the ring they sit in
       alphabetical order so two scans of the same disk yield the same
       SVG byte-for-byte.
    2. Non-hub nodes go on an **outer ring** at 80 % radius, also
       alphabetical.
    3. If a layer has more nodes than will fit on its ring, the ring
       sub-divides into concentric sub-rings.

    Determinism is load-bearing — the Mirror-Mark stamp is computed over
    the SVG bytes, so any non-determinism (e.g. dict ordering) would
    break round-trip verification.
    """
    cx, cy = width / 2, height / 2
    hub_radius = min(width, height) * 0.20
    ring_radius = min(width, height) * 0.42

    hubs = sorted([n for n in graph.all_nodes() if n in HUB_NAMES])
    others = sorted([n for n in graph.all_nodes() if n not in HUB_NAMES])

    positions: dict[str, tuple[float, float]] = {}

    # Inner ring — hubs.
    n_hubs = len(hubs)
    for i, hub in enumerate(hubs):
        if n_hubs <= 1:
            angle = -math.pi / 2
        else:
            angle = -math.pi / 2 + (2 * math.pi * i / n_hubs)
        positions[hub] = (cx + hub_radius * math.cos(angle), cy + hub_radius * math.sin(angle))

    # Outer ring — non-hubs, optionally sub-divided into multi-ring
    # spirals so a 300-node graph still fits.
    n_others = len(others)
    if n_others == 0:
        return positions
    # How many concentric sub-rings do we need? Aim for ~60 nodes per ring.
    rings = max(1, math.ceil(n_others / 60))
    per_ring = math.ceil(n_others / rings)
    for i, node in enumerate(others):
        ring_ix = i // per_ring
        idx_in_ring = i % per_ring
        in_ring_count = min(per_ring, n_others - ring_ix * per_ring)
        radius = ring_radius * (1.0 + 0.18 * ring_ix)
        if in_ring_count <= 1:
            angle = -math.pi / 2
        else:
            angle = -math.pi / 2 + (2 * math.pi * idx_in_ring / in_ring_count)
        positions[node] = (cx + radius * math.cos(angle), cy + radius * math.sin(angle))
    return positions


# ---------------------------------------------------------------------------
# Public API.
# ---------------------------------------------------------------------------

def render_svg(
    graph: Graph,
    *,
    title: str = "Limitless ecosystem dependency map",
    width: int = 1600,
    height: int = 1600,
    corpus_sha: bytes = DEV_CORPUS_SHA,
    key: bytes = DEV_KEY,
) -> str:
    """Render ``graph`` to a Mirror-Mark stamped SVG string.

    Determinism contract: for the same ``(graph, title, width, height,
    corpus_sha, key)`` inputs the function returns byte-identical output
    on Python 3.11 / 3.12 / 3.13. The stamp is computed over the SVG
    body bytes **before** the stamp comment itself is inserted, so the
    stamp is reproducible from the published SVG by stripping the first
    comment line and re-running :func:`sign`.

    Layout:

    * Title ``<text>`` top-centre at ``y=40``.
    * Liability footer text-wrapped across the bottom 6 % of canvas.
    * Edges drawn first (so nodes overlay them), substrate-coloured.
    * Cohort firewall edges (producer in :data:`FIREWALL_HUBS`) bolded.
    * Nodes drawn as circles with label below. Hubs at 18 px radius;
      every other node at 12 px.

    Returns the SVG as a UTF-8 string ready to write to disk.
    """
    svg = ET.Element(
        "svg",
        {
            "xmlns": "http://www.w3.org/2000/svg",
            "viewBox": f"0 0 {width} {height}",
            "width": str(width),
            "height": str(height),
        },
    )

    # Background fill for legibility on dark presentation surfaces.
    ET.SubElement(svg, "rect", {
        "x": "0", "y": "0",
        "width": str(width), "height": str(height),
        "fill": "#ffffff",
    })

    # Title.
    title_el = ET.SubElement(svg, "text", {
        "x": str(width // 2), "y": "40",
        "font-family": "Helvetica, Arial, sans-serif",
        "font-size": "28",
        "fill": "#222222",
        "text-anchor": "middle",
        "font-weight": "bold",
    })
    title_el.text = title

    # Metadata block — counts visible in the SVG itself.
    meta = ET.SubElement(svg, "text", {
        "x": str(width // 2), "y": "70",
        "font-family": "Helvetica, Arial, sans-serif",
        "font-size": "14",
        "fill": "#666666",
        "text-anchor": "middle",
    })
    meta.text = (
        f"nodes={graph.node_count()} edges={graph.edge_count()} "
        f"hubs={sum(1 for n in graph.all_nodes() if n in HUB_NAMES)}"
    )

    # Layout the nodes.
    positions = _layout(graph, width, height)

    # --- Edges layer -------------------------------------------------
    edges_g = ET.SubElement(svg, "g", {"id": "edges"})
    for edge in sorted(graph.edges, key=lambda e: (e.consumer, e.producer, e.kind)):
        cpos = positions.get(edge.consumer)
        ppos = positions.get(edge.producer)
        if cpos is None or ppos is None:
            continue
        is_firewall = edge.producer in FIREWALL_HUBS
        stroke = SUBSTRATE_STROKE.get(edge.kind, "")
        stroke_width = "3.0" if is_firewall else "1.0"
        color = "#c0392b" if is_firewall else "#7f8c8d"
        opacity = "0.85" if is_firewall else "0.55"
        attrs = {
            "x1": f"{cpos[0]:.2f}", "y1": f"{cpos[1]:.2f}",
            "x2": f"{ppos[0]:.2f}", "y2": f"{ppos[1]:.2f}",
            "stroke": color,
            "stroke-width": stroke_width,
            "stroke-opacity": opacity,
        }
        if stroke:
            attrs["stroke-dasharray"] = stroke
        ET.SubElement(edges_g, "line", attrs)

    # --- Nodes layer -------------------------------------------------
    nodes_g = ET.SubElement(svg, "g", {"id": "nodes"})
    for node in sorted(graph.all_nodes()):
        x, y = positions[node]
        kind = graph.node_kinds.get(node, NodeKind.UNKNOWN)
        fill = NODE_FILL.get(kind, NODE_FILL[NodeKind.UNKNOWN])
        # Hubs render larger to signal degree-centrality.
        r = 18.0 if node in HUB_NAMES else 12.0
        # Foundation-prefixed names render as hubs too.
        if node.startswith("foundation/"):
            r = 18.0
        ET.SubElement(nodes_g, "circle", {
            "cx": f"{x:.2f}", "cy": f"{y:.2f}",
            "r": f"{r:.1f}",
            "fill": fill,
            "stroke": "#222222",
            "stroke-width": "1.0",
        })
        label = ET.SubElement(nodes_g, "text", {
            "x": f"{x:.2f}",
            "y": f"{y + r + 12:.2f}",
            "font-family": "Helvetica, Arial, sans-serif",
            "font-size": "10",
            "fill": "#222222",
            "text-anchor": "middle",
        })
        label.text = node

    # --- Legend ------------------------------------------------------
    legend_g = ET.SubElement(svg, "g", {"id": "legend"})
    legend_items = [
        (NodeKind.FLAGSHIP, "flagship"),
        (NodeKind.INFRASTRUCTURE, "infrastructure"),
        (NodeKind.ENGINE, "engine"),
        (NodeKind.FOUNDATION, "foundation"),
        (NodeKind.SDK, "sdk"),
        (NodeKind.HUB, "hub"),
        (NodeKind.UNKNOWN, "unknown"),
    ]
    legend_x = 40
    legend_y = 110
    for i, (kind, label) in enumerate(legend_items):
        y = legend_y + i * 28
        ET.SubElement(legend_g, "circle", {
            "cx": str(legend_x),
            "cy": str(y),
            "r": "10",
            "fill": NODE_FILL[kind],
            "stroke": "#222222",
            "stroke-width": "1.0",
        })
        text = ET.SubElement(legend_g, "text", {
            "x": str(legend_x + 22),
            "y": str(y + 5),
            "font-family": "Helvetica, Arial, sans-serif",
            "font-size": "14",
            "fill": "#222222",
        })
        text.text = label

    # Firewall callout in the legend.
    fw_y = legend_y + len(legend_items) * 28 + 12
    ET.SubElement(legend_g, "line", {
        "x1": str(legend_x - 10), "y1": str(fw_y),
        "x2": str(legend_x + 10), "y2": str(fw_y),
        "stroke": "#c0392b", "stroke-width": "3.0",
    })
    fw_text = ET.SubElement(legend_g, "text", {
        "x": str(legend_x + 22), "y": str(fw_y + 5),
        "font-family": "Helvetica, Arial, sans-serif",
        "font-size": "14",
        "fill": "#222222",
    })
    fw_text.text = "R145.C cohort firewall edge"

    # --- Footer (R166 liability) ------------------------------------
    footer_g = ET.SubElement(svg, "g", {"id": "footer"})
    footer_lines = _wrap_text(LIABILITY_FOOTER, max_chars=140)
    base_y = height - (len(footer_lines) * 14) - 16
    for i, line in enumerate(footer_lines):
        text = ET.SubElement(footer_g, "text", {
            "x": str(width // 2),
            "y": str(base_y + i * 14),
            "font-family": "Helvetica, Arial, sans-serif",
            "font-size": "11",
            "fill": "#555555",
            "text-anchor": "middle",
        })
        text.text = line
    # Footer tag (machine-readable).
    tag = ET.SubElement(footer_g, "text", {
        "x": str(width // 2),
        "y": str(height - 6),
        "font-family": "Helvetica, Arial, sans-serif",
        "font-size": "9",
        "fill": "#888888",
        "text-anchor": "middle",
    })
    tag.text = f"audit_rule={LIABILITY_TAG}"

    # Serialise body without the Mirror-Mark comment.
    body_bytes = ET.tostring(svg, encoding="utf-8")

    # Compute the Mirror-Mark over the body bytes.
    mark = sign(corpus_sha, body_bytes, key)

    # Final document: XML declaration + Mirror-Mark comment + body.
    xml_decl = b'<?xml version="1.0" encoding="UTF-8"?>\n'
    mark_comment = f'<!-- {mark} corpus_sha={corpus_sha.hex()[:16]}... audit_rule=L43_MIRROR_MARK_V1 -->\n'.encode(
        "utf-8"
    )
    return (xml_decl + mark_comment + body_bytes + b"\n").decode("utf-8")


def extract_mark(svg_text: str) -> str:
    """Pull the ``lore@v1:`` mark out of an SVG produced by :func:`render_svg`.

    Returns the full ``lore@v1:...`` mark string, or raises ``ValueError``
    if the SVG lacks a stamp comment. Used by the test suite to confirm
    round-trip verifiability.
    """
    for line in svg_text.splitlines():
        s = line.strip()
        if s.startswith("<!--") and MARK_PREFIX in s:
            start = s.index(MARK_PREFIX)
            rest = s[start:]
            # Mark ends at first whitespace.
            end = rest.find(" ")
            if end == -1:
                end = rest.find("-->")
            return rest[:end].strip()
    raise ValueError("SVG lacks a Mirror-Mark stamp comment")


def _wrap_text(text: str, max_chars: int = 80) -> list[str]:
    """Hard-wrap ``text`` at word boundaries for SVG ``<text>`` rendering."""
    words = text.split()
    lines: list[str] = []
    cur: list[str] = []
    cur_len = 0
    for w in words:
        if cur_len + len(w) + (1 if cur else 0) > max_chars:
            if cur:
                lines.append(" ".join(cur))
            cur = [w]
            cur_len = len(w)
        else:
            cur.append(w)
            cur_len += len(w) + (1 if cur_len else 0)
    if cur:
        lines.append(" ".join(cur))
    return lines
